config/routes.rb
Rails.application.routes.draw do
  root to: 'quizzes#new'
  resources :quizzes, only: [:create, :show] do
    resources :answers, only: [:new, :create]
  end
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  quiz_id     :integer
#  question_id :integer
#  responce    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  candidate_1 :integer
#  candidate_2 :integer
#

class Answer < ApplicationRecord
  belongs_to :quiz
  belongs_to :question

  # enum responce: [:slytherin, :hufflepuff, :ravenclaw, :gryffindor]

  def winner
    responce == candidate_1 ? candidate_1 : candidate_2
  end

  def looser
    responce == candidate_1 ? candidate_2 : candidate_1
  end

  def responce_code
    case responce
      when 0
        :green
      when 1
        :yellow
      when 2
        :blue
      when 3
        :red
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id           :integer          not null, primary key
#  topic_url    :string
#  answer_s_url :string
#  answer_h_url :string
#  answer_r_url :string
#  answer_g_url :string
#

class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :quizzes, through: :answers

  def answer(int)
    case int
      when 1
        answer_s_url
      when 2
        answer_h_url
      when 3
        answer_r_url
      when 4
        answer_g_url
    end
  end
end

app/models/quiz.rb
# == Schema Information
#
# Table name: quizzes
#
#  id         :integer          not null, primary key
#  uid        :string
#  finished   :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Quiz < ApplicationRecord
  has_many :answers, dependent: :destroy
  has_many :questions, through: :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @quiz = Quiz.find(params[:quiz_id])
    operator = QuizzOperator.new(@quiz)
    if operator.finished?
      MicroCommute.publish(operator.verdict)
      redirect_to quiz_path(@quiz)
    else
      answer = @quiz.answers.where(responce: nil).first
      answer = answer || operator.select_question
      @question = answer.question
      @answ1 = answer.candidate_1
      @answ2 = answer.candidate_2
    end
  end

  def create
    @quiz = Quiz.find(params[:quiz_id])
    operator = QuizzOperator.new(@quiz)
    operator.accept_answer(params[:answer])
    if operator.finished?
      redirect_to quiz_path(@quiz)
    else
      redirect_to new_quiz_answer_path(@quiz)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def new
    @quiz = ::Faker::HarryPotter.character.parameterize(separator: '_')
  end

  def create
    quiz_id = params[:quiz]
    quiz = Quiz.create(uid: quiz_id)
    redirect_to new_quiz_answer_path(quiz)
  end

  def show
    @quiz = Quiz.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/new.html.erb
<table align="center">
  <tr>
    <td align="center" colspan="2">
      <%= 'image_tag @question.topic_url' %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to 'image_tag(@question.answer(@answ1))', quiz_answers_path(quiz: @quiz, answer: @answ1), method: :post %></td>
    <td>
      <%= link_to 'image_tag(@question.answer(@answ2))', quiz_answers_path(quiz: @quiz, answer: @answ2), method: :post %></td>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HatTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quizzes/new.html.erb
<div>
  <center>
    <h1>
      It's a trap!
    </h1>
    <h3>
      It's a joke test. If Hogwards were programming institution you were...
    </h3>
    <%= link_to 'Find out', quizzes_path(quiz: @quiz), method: :post %>
  </center>
</div>

app/views/quizzes/show.html.erb
<div>
  <center>
    <h1>
      You're almost home
    </h1>
    <%= link_to 'Find out', '#' %>
  </center>
</div>